### ISSUE TITLE
数据类型报错

### ISSUE THREAD

**Issue by fanfanqiqi** [icey-zhang/SuperYOLO#102]
Plotting labels... 
Traceback (most recent call last):
  File "/data1/zhouyanqi/SuperYOLO-main/train.py", line 673, in <module>
    train(hyp, opt, device, tb_writer)
  File "/data1/zhouyanqi/SuperYOLO-main/train.py", line 248, in train
    tb_writer.add_histogram('classes', c, 0)
  File "/home/zminghang/anaconda3/envs/mmdet/lib/python3.8/site-packages/torch/utils/tensorboard/writer.py", line 484, in add_histogram
    histogram(tag, values, bins, max_bins=max_bins), global_step, walltime
  File "/home/zminghang/anaconda3/envs/mmdet/lib/python3.8/site-packages/torch/utils/tensorboard/summary.py", line 352, in histogram
    hist = make_histogram(values.astype(float), bins, max_bins)
  File "/home/zminghang/anaconda3/envs/mmdet/lib/python3.8/site-packages/torch/utils/tensorboard/summary.py", line 380, in make_histogram
    cum_counts = np.cumsum(np.greater(counts, 0, dtype=np.int32))
TypeError: No loop matching the specified signature and casting was found for ufunc greater

**Comment by icey-zhang** [comment]
可能是版本问题，参考https://blog.csdn.net/weixin_45819759/article/details/131229983解决
