### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy._core'

### ISSUE THREAD

**Issue by ZhaoYQ997** [icey-zhang/SuperYOLO#133]
Ubuntu22.04 & Python=3.8 & numpy==1.24.4

When I run train.py, I get a ERROR: ModuleNotFoundError: No module named 'numpy._core'

The full error information is:

```
Traceback (most recent call last):
  File "train.py", line 673, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 212, in train
    dataloader, dataset = create_dataloader(train_path, imgsz, batch_size, gs, opt,
  File "/home/rime997/SuperYOLO/utils/datasets.py", line 92, in create_dataloader_sr
    dataset = LoadImagesAndLabels_sr(path, imgsz, batch_size,
  File "/home/rime997/SuperYOLO/utils/datasets.py", line 691, in __init__
    cache = torch.load(cache_path)  # load
  File "/home/rime997/miniconda3/envs/SuperYOLO/lib/python3.8/site-packages/torch/serialization.py", line 1097, in load
    return _load(
  File "/home/rime997/miniconda3/envs/SuperYOLO/lib/python3.8/site-packages/torch/serialization.py", line 1525, in _load
    result = unpickler.load()
  File "/home/rime997/miniconda3/envs/SuperYOLO/lib/python3.8/site-packages/torch/serialization.py", line 1515, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'numpy._core'
```

I can't solve it and I hope to get some help please. Thank you!

**Comment by icey-zhang** [comment]
maybe you can search this problem in baidu
