### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by Mutopia-H** [icey-zhang/SuperYOLO#141]
```
Traceback (most recent call last):
  File "train.py", line 22, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "D:\APP\Miniconda\envs\SuperYOLO-main\lib\site-packages\torch\utils\tensorboard\__init__.py", line 4, in <module>
    LooseVersion = `distutils.version.LooseVersion`
AttributeError: module 'distutils' has no attribute 'version'
```

为什么会有这种错误，是软件包版本的问题吗？或是在Windows平台上的问题？

**Comment by Mutopia-H** [comment]
> ```
> Traceback (most recent call last):
>   File "train.py", line 22, in <module>
>     from torch.utils.tensorboard import SummaryWriter
>   File "D:\APP\Miniconda\envs\SuperYOLO-main\lib\site-packages\torch\utils\tensorboard\__init__.py", line 4, in <module>
>     LooseVersion = `distutils.version.LooseVersion`
> AttributeError: module 'distutils' has no attribute 'version'
> ```
> 
> 为什么会有这种错误，是软件包版本的问题吗？或是在Windows平台上的问题？



解决方法：网上建议 ：pip install setuptools==59.5.0
```
import tensorboard
from setuptools import distutils
 
# LooseVersion = distutils.version.LooseVersion
 
# if not hasattr(tensorboard, '__version__') or LooseVersion(tensorboard.__version__) < LooseVersion('1.15'):
#     raise ImportError('TensorBoard logging requires TensorBoard version 1.15 or above')
 
del distutils
# del LooseVersion
del tensorboard
 
from .writer import FileWriter, SummaryWriter  # noqa: F401
from tensorboard.summary.writer.record_writer import RecordWriter  # noqa: F401
```
