### ISSUE TITLE
test.py: ModuleNotFoundError: No module named 'models.deeplab'

### ISSUE THREAD

**Issue by AI-Gio** [icey-zhang/SuperYOLO#35]
Hi, I am trying to run the test code that is provided. 

Only when using the model weights "SuperYOLO_fold1_best.pt" and using the VEDAI dataset, the test.py code isn't working.

Traceback (most recent call last):
  File "C:\Users\gsvpk\VScode\Own_Projects\superOG\test.py", line 374, in <module>
    test(opt.data,
  File "C:\Users\gsvpk\VScode\Own_Projects\superOG\test.py", line 65, in test
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "C:\Users\gsvpk\VScode\Own_Projects\superOG\models\experimental.py", line 118, in attempt_load
    ckpt = torch.load(w, map_location=map_location)  # load
  File "C:\Users\gsvpk\anaconda3\envs\deeplearning\lib\site-packages\torch\serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\gsvpk\anaconda3\envs\deeplearning\lib\site-packages\torch\serialization.py", line 1172, in _load
    result = unpickler.load()
  File "C:\Users\gsvpk\anaconda3\envs\deeplearning\lib\site-packages\torch\serialization.py", line 1165, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'models.deeplab'

I have put the weights in the "weights" folder and the VEDAI/VEDAI1024 folders in the "dataset" folder. 

Do you have any idea to how this can be resolved? Thank you in advance!

**Comment by icey-zhang** [comment]
I advise you to use the new weights small_EDSR_MF
